---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/EDTC-Paid-Timeoff
  label: Edtc paid timeoff
  create: all
  match: "**/*"
- type: directory
  path: content/Links
  label: Links
  create: all
  match: "**/*"
- type: directory
  path: content/Calendars
  label: Calendars
  create: all
  match: "**/*"
- type: directory
  path: content/Payroll-WorkCenter
  label: Payroll workcenter
  create: all
  match: "**/*"
- type: directory
  path: content/FAQ
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: content/News
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/Email
  label: Email
  create: all
  match: "**/*"
- type: directory
  path: content/Forms
  label: Forms
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
